# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reset_pswd_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('token0', models.CharField(max_length=35, null=True)),
            ],
        ),
    ]
