# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostel_db',
            fields=[
                ('hostel_name', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('Y4', 'Y4'), ('I2', 'I2'), ('I3', 'I3'), ('Guest House', 'Guest House')], max_length=25, primary_key=True, serialize=False)),
                ('no_of_rooms', models.PositiveSmallIntegerField()),
                ('caretaker_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Hostel Detail',
            },
        ),
        migrations.CreateModel(
            name='password_db',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='warden_db',
            fields=[
                ('warden_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('warden_name', models.CharField(max_length=50)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('office_addr', models.TextField(max_length='200')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('chief_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Warden Detail',
            },
        ),
        migrations.CreateModel(
            name='student_db',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=80)),
                ('programme', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('M.Tech Executive', 'M.Tech Executive'), ('MBA', 'MBA'), ('PhD', 'PhD')], max_length=20)),
                ('branch', models.CharField(max_length=80)),
                ('semester', models.PositiveSmallIntegerField()),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('guardian_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('age', models.PositiveSmallIntegerField()),
                ('photo', models.BinaryField(null=True)),
                ('premanent_addr', models.TextField()),
                ('refund', models.IntegerField(default=0)),
                ('room_no', models.IntegerField()),
                ('hostel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.hostel_db')),
            ],
            options={
                'verbose_name': 'Student Detail',
            },
        ),
        migrations.AddField(
            model_name='hostel_db',
            name='warden_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.warden_db'),
        ),
    ]
