# Generated by Django 4.1.3 on 2022-11-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_student_db_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password_db',
            old_name='user_id',
            new_name='roll_no',
        ),
    ]
