# Generated by Django 4.1.3 on 2022-11-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_user_id_password_db_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_db',
            old_name='premanent_addr',
            new_name='permanent_addr',
        ),
        migrations.AlterField(
            model_name='student_db',
            name='hostel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.hostel_db'),
        ),
    ]
