# Generated by Django 4.1.3 on 2022-11-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_premanent_addr_student_db_permanent_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_db',
            name='roll_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.student_db'),
        ),
    ]
