# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_application_db',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=251)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accepted', models.BooleanField(default=None, null=True)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student_db')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications Managment',
            },
        ),
        migrations.CreateModel(
            name='complaints_db',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_type', models.CharField(choices=[('Room', 'Room Related'), ('Facility', 'Facilities Related'), ('Other', 'Other')], max_length=50)),
                ('complaint_date', models.DateField()),
                ('complaint_image', models.ImageField(null=True, upload_to='')),
                ('complaint_solved', models.BooleanField(default=False)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student_db')),
            ],
            options={
                'verbose_name': 'Complaint ',
                'verbose_name_plural': 'Complaints Managment',
            },
        ),
    ]
