# Generated by Django 4.1.3 on 2022-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_complaints_db_complaint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_db',
            name='complaint_description',
            field=models.TextField(),
        ),
    ]
