# Generated by Django 4.1.3 on 2022-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_complaints_db_complaint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application_db',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
