# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard_Detail',
            fields=[
                ('Guard_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Guard_Name', models.CharField(max_length=80)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Password', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Guard Details',
                'verbose_name_plural': 'Guards Details',
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_time', models.DateTimeField(null=True)),
                ('reason', models.CharField(max_length=200)),
                ('guard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrylog.guard_detail')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student_db')),
            ],
            options={
                'verbose_name': 'Entry Exit Details',
            },
        ),
        migrations.CreateModel(
            name='Defaulters',
            fields=[
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entrylog.entrylog')),
                ('is_resolved', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student_db')),
            ],
            options={
                'verbose_name': 'Student Outside Campus',
                'verbose_name_plural': 'Students Outside Campus',
            },
        ),
    ]
