# Generated by Django 4.1.3 on 2022-11-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaulters',
            options={'verbose_name': 'Defaulter', 'verbose_name_plural': 'Defaulters'},
        ),
        migrations.AlterModelOptions(
            name='entrylog',
            options={'verbose_name': 'Entry Log', 'verbose_name_plural': 'Entry Exit Details'},
        ),
    ]
