# Generated by Django 4.1.3 on 2022-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0002_alter_defaulters_options_alter_entrylog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
