# Generated by Django 4.1.3 on 2022-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0003_alter_entrylog_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulters',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
